### ISSUE TITLE
tracking linkuri "targetare" pt. Scrapers_canghelet

### ISSUE THREAD

**Issue by davidmondoc** [peviitor-ro/Scrapers-UI#122]
**1. chainIQ** (tester **_DAVID_**)
- [x] adaugare link targetare
- [x] adaugare link cariere
- [x] trimis bug: nu se incarca scraperul
- [x] de re-testa dupa rezolvare

**2. DP World** (tester **_DAVID_**)
- [x] adaugare link targetare
- [x] adaugare link cariere
- [x] apare firma de 2 ori pe firme.peviitor.ro = am trimis bug. de verificat daca s-a rezolvat

**3. Hogarth** 
- [x] adaugare link targetare
- [x] adaugare link cariere

**4. Magna** (tester **_DAVID_**)
- [x] adaugare link targetare
- [x] adaugare link cariere
- [x]  apare firma de 2 ori pe firme.peviitor.ro = am trimis bug. de verificat daca s-a rezolvat

**5. NewEraTechnology** (tester **_LUIZA_**)
- [x] adaugare link targetare 
- [x] adaugare link cariere
- [x] lipsește diagrama = am trimis bug de verificat dacă s-a rezolvat
- [x] eroare nume companie = am trimis bug de verificat dacă s-a rezolvat

**6. Onapsis**
- [x] adaugare link targetare
- [x] adaugare link cariere

**7.PlanNet** (tester **_LUIZA_**)
- [x] adaugare link targetare
- [x] adaugare link cariere
- [ ] lipseste logo = am trimis bug de verificat dacă s-a rezolvat 

**8.  Sofidel**
- [x] adaugare link targetare
- [x] adaugare link cariere

**9. SugarCRM** (tester **_LUIZA_**)
- [x] adaugare link targetare
- [x] adaugare link cariere
- [x] lipsește diagrama = am trimis bug de verificat dacă s-a rezolvat
- [x] eroare nume companie = am trimis bug de verificat dacă s-a rezolvat

**10. Vass (VASSEUSERVICES)** (tester **_LUIZA_**)
- [x] adaugare link targetare **_### nu apare pe targetare.ro_**
- [x] adaugare link cariere
- [x] logo
- [ ] joburi nu corespund cu cele de peviitor.ro

**11. VitaminSoftware**
- [x] adaugare link targetare
- [x] adaugare link cariere

**12. Urban Socializing** (tester **_LUIZA_**)
- [x] adaugare link targetare
- [x] adaugare link cariere
- [ ] joburile nu corespund

**13. OPIS**
- [x] adaugare link targetare
- [x] adaugare link cariere

**14. Tufin**
- [x] adaugare link targetare
- [x] adaugare link cariere

**15. TAIN**
- [ ] adaugare link targetare
- [x] adaugare link cariere

**16. 3SS**
- [ ] adaugare link targetare
- [ ] adaugare link cariere
